### PR TITLE
feat: Table cell/column widths in API

### LINKED ISSUE #655: Table doesn't save columns width after refresh
**Describe the bug**
Table doesn't save columns width after refresh

**To Reproduce**
I resize the columns width for editor table. 
After that I save the content to the api ( I save all the content that editor return in editor.topLevelBlocks from onEditorContentChange ), but after refresh table has the default width for column
It happens because the styles object is empty and there is no information for updated column width

How can I pass column width from editor table to styles object?

**Misc**
- Node version: 20.9.0
- Package manager: npm 
- Browser: Chrome
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

### PR DESCRIPTION
**Pull request by matthewlipski**
You can already resize table cells in BlockNote, but these use premade TipTap nodes and so their widths are not really accessible to get/set via the BlockNote API. This PR modifies the typing of `TableContent` so that you can now read and update table cell widths. Additionally, it fixes a small bug that was preventing the cell widths from being parsed correctly.

The changes I made are based on #846, but I don't have push rights to that remote repo so this PR replaces that one.

Closes #655

### CODE REVIEW

**Review by YousefED — COMMENTED** [review]
Hmm, downside is that this would break all existing documents stored right? Let's think a bit more about backwards compatibility before merging this

**Comment by halimt92** [comment]
> Hmm, downside is that this would break all existing documents stored right? Let's think a bit more about backwards compatibility before merging this

If you guys use a minWidth of 100px and change the minWidth of the paragraphs instead of the width, it would not affect the existing tables right @YousefED ?

**Comment by matthewlipski** [comment]
> > Hmm, downside is that this would break all existing documents stored right? Let's think a bit more about backwards compatibility before merging this
> 
> If you guys use a minWidth of 100px and change the minWidth of the paragraphs instead of the width, it would not affect the existing tables right @YousefED ?

It's not quite that simple - the width of the table cells was/is already stored within TipTap's `TableCell` node, this PR is more about exposing that to the BlockNote API so the widths are preserved when saving and loading the doc. But because we're adding a width to table cells in the API, the type definition of `CellContent` needs to be changed and so existing documents with the previous `CellContent` implementation will break.

**Comment by matthewlipski** [comment]
Also just to add, it is a good point that cells should have a minimum width (should be able to extend the `TableCell` node with `addAttributes` to do that), and we should make sure to do that before merging because right now it makes the UX pretty janky.

**Review by osawa-koki — APPROVED** [review]

**Pull request closed without merging**
