### PR TITLE
fix: Slash Command Android Chrome Issue  #437 

### PR DESCRIPTION
**Pull request by Kashifwahaj**
Hi,
I investigated the issue, The `handleKeyDown` event is not returning properly updated objects on the Android Chrome browser, so I think we need to use the `handleTextInput` method to fix this.

Thanks

### CODE REVIEW

**Comment by matthewlipski** [comment]
Nice find! Do you think you could just extract the code into a separate function? Since seems like it's basically the same as for the `handleKeyDown` handler, so would be great if we could use the same code for both

**Comment by Kashifwahaj** [comment]
> Nice find! Do you think you could just extract the code into a separate function? Since seems like it's basically the same as for the `handleKeyDown` handler, so would be great if we could use the same code for both

Thanks for the suggestion, I updated and pushed the code.

**Comment by Kashifwahaj** [comment]
@matthewlipski is there anything else you suggest for this PR ?

**Comment by Kashifwahaj** [comment]
@matthewlipski ?

**Comment by Kashifwahaj** [comment]
@matthewlipski @YousefED Please can we proceed with this PR, let me know if any improvement or changes required

**Review by matthewlipski — APPROVED** [review]

**Comment by YousefED** [comment]
@matthewlipski did you check if we still need both handlers?

**Pull request merged**
