### PR TITLE
feat: implemented trailingBlock option

### PR DESCRIPTION
**Pull request by ezhil56x**
Updated `BlockNoteExtension.ts` to configure TrailingNode extension, introducing trailingBlock option for controlling insertion of trailing block nodes. Default behavior remains unchanged with trailingBlock set to true for inserting trailing block nodes at the end of the document.

/claim #631

### CODE REVIEW

**Comment by ezhil56x** [comment]
Can you review once?, thanks!
@YousefED

**Comment by ezhil56x** [comment]
@YousefED 
Can you review once?
Thanks!

**Comment by ezhil56x** [comment]
https://github.com/TypeCellOS/BlockNote/assets/103899034/17bee834-a92d-41c6-bbaf-7b01339e97e4

**Review by YousefED — COMMENTED** [review]
there's no way now to make this configurable. For now #679 seems like a better approach

**Comment by YousefED** [comment]
closed in favor of #679

**Pull request closed without merging**
