### PR TITLE
fix: dev-script failing in windows issue

### PR DESCRIPTION
**Pull request by rogueloop**
/claim https://github.com/TypeCellOS/BlockNote/issues/955
close https://github.com/TypeCellOS/BlockNote/issues/955

### CODE REVIEW

**Comment by zaaakher** [comment]
I just tested it on both Windows 10 and MacOS and here are the current results


| OS      | Updates `examples.gen.tsx` | Adds example files |
| ------- | ------------------------ | ------------------ |
| Windows | ✅                       | ❌                 |
| MacOS   | ✅                       | ✅                 |



By "adds example files" I mean the `package.json`, `tsconfig.json`, `index.html`, `main.tsx`, and `vite.config.ts` in each example folder that should be automatically generated by the script.


Note: I copied the above text from my response to the other PR about the same issue because it's actually the same case scenario.

**Comment by rogueloop** [comment]
https://github.com/user-attachments/assets/9c7cc844-3578-491e-b849-3a92183f460a

Addressed the issues @zaaakher

**Comment by zaaakher** [comment]
@rogueloop I just tested again and it's working well just as expected 👍 

| OS      | Updates `examples.gen.tsx` | Adds example files |
| ------- | ------------------------ | ------------------ |
| Windows | ✅                       | ✅                 |
| MacOS   | ✅                       | ✅                 |

**Comment by rogueloop** [comment]
Ready for a review

**Pull request closed without merging**
