### PR TITLE
Image blocks

### PR DESCRIPTION
**Pull request by matthewlipski**

### CODE REVIEW

**Comment by jesusmariocalleja** [comment]
This would be awesome. How is the image addition handled? Paste, drag & drop...?

**Comment by CyrusZei** [comment]
any update on this?

**Comment by dotknyl** [comment]
waiting for you :partying_face:

**Comment by abhikhedekar4241** [comment]
When will this PR be merged?

**Comment by sylviangth** [comment]
looking forward to it 🚀

**Comment by matthewlipski** [comment]
Closing this PR, a new & improved implementation for image blocks is in #331

**Pull request closed without merging**
